// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('loadProductDetails', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('loadProductDetails', async function() {
    await driver.get("https://team45salesapp.tk/")
    await driver.manage().window().setRect({ width: 1288, height: 780 })
    await driver.findElement(By.css(".col-lg-3:nth-child(2) .btn")).click()
    {
      const elements = await driver.findElements(By.css(".mt-5"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css("tr:nth-child(1) > th"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css("tr:nth-child(2) > th"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".mt-4"))
      assert(elements.length)
    }
  })
})
