// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Load Products', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Load Products', async function() {
    await driver.get("https://team45salesapp.tk/")
    await driver.manage().window().setRect({ width: 1288, height: 780 })
    {
      const elements = await driver.findElements(By.css(".col-lg-3:nth-child(3) .ms-card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".mt-4"))
      assert(elements.length)
    }
  })
})
