// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register', async function() {
    await driver.get("https://team45salesapp.tk/")
    await driver.manage().window().setRect({ width: 1288, height: 780 })
    await driver.findElement(By.linkText("Sign Up")).click()
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("test")
    await driver.findElement(By.id("lastName")).click()
    await driver.findElement(By.id("lastName")).sendKeys("test")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("teset@gmail.com")
    await driver.findElement(By.id("pasword")).sendKeys("P@ssword123")
    await driver.findElement(By.id("dob")).sendKeys("0001-12-12")
    await driver.findElement(By.id("dob")).sendKeys("0019-12-12")
    await driver.findElement(By.id("dob")).sendKeys("0199-12-12")
    await driver.findElement(By.id("dob")).sendKeys("1992-12-12")
    await driver.findElement(By.css(".w-100")).click()
    await driver.close()
  })
})
