// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search products', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search products', async function() {
    await driver.get("https://team45salesapp.tk/")
    await driver.manage().window().setRect({ width: 1288, height: 780 })
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("vegetables")
    await driver.findElement(By.css(".btn-outline-success")).click()
    assert(await driver.findElement(By.css(".col-lg-3:nth-child(1) .wrapper-new1 > span")).getText() == "Category : Vegetables")
  })
})
